name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/odsquizauth:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/odsquizauth:latest

  delete-branch:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Delete branch after merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          REPO: ${{ github.repository }}
        run: |
          echo "Deleting branch: $BRANCH from repo: $REPO"
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH

